script:
- git clone https://github.com/wy-ei/wy-ei.github.io.git --depth 1
- cd wy-ei.github.io
- git config --global user.email "nameiswangyu@163.com"
- git config --global user.name "wangyu"
- git submodule init
- cd _posts
- git pull origin master
- cd ..
- git add .
- git commit -m "update"
- git push --quiet "https://$GH_TOKEN@github.com/wy-ei/wy-ei.github.io.git" master
