script:
- git clone --depth=1 https://github.com/wy-ei/wy-ei.github.io.git
- cd wy-ei.github.io
- git config --global user.email "nameiswangyu@163.com"
- git config --global user.name "wangyu"
- git submodule init
- git submodule update --remote
- cd _posts
- git pull origin master
- cd ..
- git add .
- git commit -m "update"
- git push --quiet "https://$GH_TOKEN@github.com/wy-ei/wy-ei.github.io.git" master
